# Generated by Django 5.2.7 on 2025-11-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_admin_type_alter_user_phone'),
        ('users', '0007_promote_superuser'),
    ]

    operations = [
    ]
