# Generated by Django 5.2.7 on 2025-11-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20251116_1647'),
    ]

    operations = [
    ]
