# Generated by Django 5.2.7 on 2025-11-17 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_fix_null_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleupgraderequest',
            options={},
        ),
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_users', models.BooleanField(default=True)),
                ('can_view_role_requests', models.BooleanField(default=True)),
                ('can_approve_role_requests', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Upgrade Request',
                'verbose_name_plural': 'Role Upgrade Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
