# Generated by Django 5.2.7 on 2025-11-17 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_roleupgraderequest_options_adminpermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpermission',
            options={'verbose_name': 'Admin Permission', 'verbose_name_plural': 'Admin Permissions'},
        ),
        migrations.AlterModelOptions(
            name='roleupgraderequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Role Upgrade Request', 'verbose_name_plural': 'Role Upgrade Requests'},
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
